source 'https://rubygems.org'

gem 'grape-app'

group 'development' do
  gem 'rake'
end

group 'development', 'test' do
  gem 'rspec'
end

group 'test' do
  gem 'airborne'
  gem 'database_cleaner'
  gem 'factory_girl'
  gem 'faker'
  gem 'rspec-collection_matchers'
  gem 'rspec-its'
  gem 'shoulda-matchers'
end
