require 'bundler/setup'
require 'rspec/core/rake_task'
require 'grape/app/tasks'

RSpec::Core::RakeTask.new(:spec)
task default: :spec

desc 'Launch console'
task console: :environment do
  ::ARGV.clear

  require 'irb'
  require 'irb/completion'

  IRB.start(Grape::App.root.to_s)
end
