inherit_gem:
  rubocop-bsm:
    - default.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: "2.7"
Metrics/ParameterLists:
  Exclude:
    - lib/grape/app/helpers/caching.rb
Rake/Desc:
  Enabled: false
